/** All Preconfigued Mothertoungues / Languages */
const Languages: { name: string }[] = [
  { name: "Angika" },
  { name: "Arunachali" },
  { name: "Assamese" },
  { name: "Awadhi" },
  { name: "Badaga" },
  { name: "Bengali" },
  { name: "Bhojpuri" },
  { name: "Bihari" },
  { name: "Brij" },
  { name: "Chatisgarhi" },
  { name: "Dogri" },
  { name: "English" },
  { name: "French" },
  { name: "Garhwali" },
  { name: "Garo" },
  { name: "Gujarati" },
  { name: "Haryanvi" },
  { name: "Himachalihari" },
  { name: "Hindi" },
  { name: "Kanauji" },
  { name: "Kannada" },
  { name: "Kashmiri" },
  { name: "Khandesi" },
  { name: "Khasi" },
  { name: "Konkani" },
  { name: "Koshali" },
  { name: "Kutchi" },
  { name: "Ladacki" },
  { name: "Lepcha" },
  { name: "Magahi" },
  { name: "Maithili" },
  { name: "Malayalam" },
  { name: "Manipuri" },
  { name: "Marathi" },
  { name: "Marwari" },
  { name: "Miji" },
  { name: "Mizo" },
  { name: "Monpa" },
  { name: "Nepali" },
  { name: "Nicobarese" },
  { name: "Oriya" },
  { name: "Punjabi" },
  { name: "Rajasthani" },
  { name: "Sanskrit" },
  { name: "Santhali" },
  { name: "Sindhi" },
  { name: "Sourashtra" },
  { name: "Tamil" },
  { name: "Telugu" },
  { name: "Tripuri" },
  { name: "Tulu" },
  { name: "Urdu" },
];

/** All Castes and Subcastes */
const Castes: {
  caste: string;
  subCaste: string[];
}[] = [
  { caste: "24 Manai Telugu Chettiar", subCaste: [] },
  { caste: "Ad Dharmi", subCaste: [] },
  { caste: "Adi Andhra", subCaste: [] },
  { caste: "Aggarwal", subCaste: ["Bisa Agarwal", "Gulahre"] },
  { caste: "Agri", subCaste: [] },
  { caste: "Ahir", subCaste: [] },
  { caste: "Ahom", subCaste: [] },
  { caste: "Ambalavasi", subCaste: ["Pisharody", "Poduval"] },
  { caste: "Amma Kodava", subCaste: [] },
  { caste: "Arakh Arakvanshiya", subCaste: [] },
  { caste: "Arekatica", subCaste: [] },
  { caste: "Arora", subCaste: [] },
  { caste: "Arunthathiyar", subCaste: [] },
  { caste: "Arya Vysya", subCaste: [] },
  { caste: "Ayyaraka", subCaste: [] },
  { caste: "Badaga", subCaste: [] },
  { caste: "Badhai", subCaste: [] },
  { caste: "Bagdi", subCaste: [] },
  { caste: "Baghel Gaderiya", subCaste: [] },
  { caste: "Bahi", subCaste: [] },
  { caste: "Baidya", subCaste: [] },
  { caste: "Baishnab", subCaste: [] },
  { caste: "Baishya", subCaste: [] },
  { caste: "Bajantri", subCaste: [] },
  {
    caste: "Balija",
    subCaste: [
      "Balija Naidu",
      "Balija Reddy",
      "Kavara",
      "Setti Balija",
      "Surya Balija",
      "Vada Balija",
      "Waada Balija",
    ],
  },
  { caste: "Balija Naidu", subCaste: [] },
  { caste: "Banayat Oriya", subCaste: [] },
  {
    caste: "Bania",
    subCaste: [
      "Agarwal",
      "Agrahari",
      "Asathi",
      "Baniya Kumuti",
      "Barnwals",
      "Choudharys",
      "Dosar Dusra",
      "Gahoi",
      "Gandha Vanika",
      "Gupta",
      "Jaiswal",
      "Kalwar",
      "Kanojia Kanu",
      "Kanykubj Bania",
      "Kasaundhan",
      "Keshris Kesarwani",
      "Khandelwal",
      "Komti Arya Vaishya",
      "Lad",
      "Madhesiya Kawa Halwai",
      "Mahajan",
      "Modh Ghanchi",
      "Modi",
      "Nema",
      "Oswal",
      "Padmavati Porwal",
      "Patwa",
      "Patwa",
      "Porwal Porwar",
      "Rastogi",
      "Rathi",
      "Rauniars",
      "Rauniyar",
      "Shaw Sahu Teli",
      "Sinduriya",
      "Sudi Suri Sundhi Shaundik",
      "Ummar Umre Bagaria",
      "Vaishnav",
      "Varshneys",
      "Vijayvargia",
    ],
  },
  { caste: "Banik", subCaste: [] },
  { caste: "Banjara", subCaste: [] },
  { caste: "Barai", subCaste: [] },
  { caste: "Bari", subCaste: [] },
  { caste: "Barujibi", subCaste: [] },
  { caste: "Beldar", subCaste: [] },
  { caste: "Besta", subCaste: [] },
  { caste: "Bhajantri", subCaste: [] },
  { caste: "Bhandari", subCaste: [] },
  { caste: "Bhatia", subCaste: [] },
  { caste: "Bhatraju", subCaste: [] },
  { caste: "Bhavsar", subCaste: [] },
  { caste: "Bhovi Bhoi", subCaste: [] },
  { caste: "Bhoyar", subCaste: [] },
  { caste: "Bhulia Meher", subCaste: [] },
  { caste: "Billava", subCaste: [] },
  { caste: "Bisa Agarwal", subCaste: [] },
  { caste: "Bishnoi Vishnoi", subCaste: [] },
  { caste: "Bondili", subCaste: [] },
  { caste: "Boyer", subCaste: [] },
  { caste: "Brahmakshatriya", subCaste: [] },
  { caste: "Brahmbatt", subCaste: [] },
  {
    caste: "Brahmin",
    subCaste: [
      "Anavil",
      "Andhra",
      "Audichya",
      "Bajkhedwal",
      "Bardai",
      "Barendra",
      "Bhargava",
      "Bhatt",
      "Bhumihar",
      "Brahacharanam",
      "BrahmBhatt",
      "Brajastha Maithil",
      "Dadhich",
      "Daivadnya",
      "Danua",
      "Deshastha",
      "Devrukhe",
      "Dhiman",
      "Dravida",
      "Embrandiri",
      "Garhwali",
      "Gaud Saraswat (GSB)",
      "Gaur",
      "Goswami",
      "Gujar",
      "Gujrati",
      "Gurukkal",
      "Halua",
      "Havyaka",
      "Hoysala",
      "Iyengar",
      "Iyer",
      "Jangid",
      "Jangra",
      "Jhadua",
      "Jhijhotiya",
      "Jogi",
      "Kannada",
      "Kanyakubj",
      "Karhade",
      "Kashmiri Pandit",
      "Khadayat",
      "Khandelwal",
      "Khedaval",
      "Koknastha",
      "Kota",
      "Kulin",
      "Kumaoni",
      "Madhwa",
      "Maithil",
      "Malviya",
      "Marwari",
      "Mevada",
      "Modh",
      "Mohyal",
      "Nagar",
      "Namboodiri",
      "Niyogi",
      "Paliwal",
      "Panda",
      "Pandit",
      "Panicker",
      "Pareek",
      "Pushkarna",
      "Rajasthani",
      "Rajgor",
      "Rigvedi",
      "Rudraj",
      "Sachora",
      "Sakaldwipi",
      "Sanadya",
      "Sanchihar",
      "Sanketi",
      "Saraswat",
      "Sarotri",
      "Sarua",
      "Saryuparin",
      "Shivalli",
      "Shrimali",
      "Sikhwal",
      "Smartha",
      "Sri Vishnava",
      "Stanika",
      "Tapodhan",
      "Tyagi",
      "Utkal",
      "Vaidiki",
      "Vaikhanasa",
      "Vaikhawas",
      "Vaishnav",
      "Valam",
      "Velanadu",
      "Viswa",
      "Vyas",
      "Yajurvedi",
      "Zalora",
    ],
  },
  { caste: "Chalawadi Holeya", subCaste: [] },
  { caste: "Chamar", subCaste: [] },
  { caste: "Chambhar", subCaste: [] },
  { caste: "Chandravanshi Kahar", subCaste: [] },
  { caste: "Charan", subCaste: [] },
  { caste: "Chasa", subCaste: [] },
  { caste: "Chattada Sri Vaishnava", subCaste: [] },
  { caste: "Chaudary", subCaste: [] },
  { caste: "Chaurasia", subCaste: [] },
  { caste: "Chennadasar", subCaste: [] },
  { caste: "Cheramar", subCaste: [] },
  {
    caste: "Chettiar",
    subCaste: [
      "Achirapakkam Chettiar",
      "Agaram Vellan Chettiar",
      "Ayira Vysya",
      "Beri Chettiar",
      "Elur Chetty",
      "Kasukara",
      "Kongu Chettiar",
    ],
  },
  { caste: "Chhetri", subCaste: [] },
  { caste: "Chippolu Mera", subCaste: [] },
  { caste: "CKP", subCaste: [] },
  { caste: "Coorgi", subCaste: [] },
  { caste: "Dasapalanjika Kannada Saineegar", subCaste: [] },
  { caste: "Deshastha Maratha", subCaste: [] },
  { caste: "Devadigas", subCaste: [] },
  { caste: "Devang Koshthi", subCaste: [] },
  { caste: "Devendra Kula Vellalar", subCaste: [] },
  { caste: "Devipujak (Vaghri)", subCaste: [] },
  { caste: "Dhangar", subCaste: [] },
  { caste: "Dheevara", subCaste: [] },
  { caste: "Dhobi", subCaste: [] },
  { caste: "Dhor", subCaste: [] },
  { caste: "Dommala", subCaste: [] },
  { caste: "Dumal", subCaste: [] },
  { caste: "Dusadh", subCaste: [] },
  { caste: "Edigas", subCaste: [] },
  { caste: "Ezhava", subCaste: [] },
  { caste: "Ezhuthachan", subCaste: [] },
  { caste: "Gabit", subCaste: [] },
  { caste: "Gangai Ganesh", subCaste: [] },
  { caste: "Ganiga", subCaste: [] },
  { caste: "Garhwali", subCaste: [] },
  { caste: "Gatti", subCaste: [] },
  { caste: "Gavali", subCaste: [] },
  { caste: "Gavandi", subCaste: [] },
  { caste: "Gavara", subCaste: [] },
  { caste: "Ghisadi", subCaste: [] },
  { caste: "Ghumar", subCaste: [] },
  { caste: "Goala", subCaste: [] },
  { caste: "Goan", subCaste: [] },
  { caste: "Gomantak Maratha", subCaste: [] },
  { caste: "Gond Gondi Raj Gond", subCaste: [] },
  { caste: "Gondhali", subCaste: [] },
  { caste: "Gopal", subCaste: [] },
  { caste: "Goud", subCaste: [] },
  { caste: "Gounder", subCaste: [] },
  { caste: "Gowda", subCaste: [] },
  { caste: "Gramani", subCaste: [] },
  { caste: "Gudia", subCaste: [] },
  { caste: "Gujjar", subCaste: [] },
  {
    caste: "Gupta",
    subCaste: [
      "Agrahari",
      "Asathi",
      "Ayodhyavasi",
      "Barnwals",
      "Choudharys",
      "Dosar Dusra",
      "Gahoi",
      "Gandha Vanika",
      "Gulahre",
      "Jaiswal",
      "Kalwar",
      "Kandu Kanu",
      "Kasaundhan",
      "Keshris Kesarwani",
      "Khandelwal",
      "Komti Arya Vaishya",
      "Lad",
      "Madhesiya Kawa Halwai",
      "Mahajan",
      "Modi",
      "Nema",
      "Oswal",
      "Padmavati Porwal",
      "Patwa",
      "Porwal Porwar",
      "Rastogi",
      "Rathi",
      "Rauniars",
      "Shaw Sahu Teli",
      "Ummar Umre Bagaria",
      "Vaishnav",
      "Varshneys",
      "Vijayvargia",
    ],
  },
  { caste: "Gurav", subCaste: [] },
  { caste: "Halba Koshti", subCaste: [] },
  { caste: "Hegde", subCaste: [] },
  { caste: "Helava", subCaste: [] },
  { caste: "Jaalari", subCaste: [] },
  { caste: "Jaiswal", subCaste: [] },
  { caste: "Jandra", subCaste: [] },
  { caste: "Jangam", subCaste: [] },
  {
    caste: "Jat",
    subCaste: [
      "Agharia",
      "Agoh",
      "Agra",
      "Ahlawat",
      "Alwal",
      "Antil Antal",
      "Arya",
      "Badhwar",
      "Bagaria",
      "Bagri",
      "Bains",
      "Balhara",
      "Balyan",
      "Bana",
      "Barach",
      "Bargoti",
      "Beniwal",
      "Bhal",
      "Bhambu",
      "Bhodu",
      "Bomal",
      "Budania",
      "Bugaliya",
      "Burdak",
      "Chahal",
      "Chaudhry",
      "Chauhan",
      "Chhikara Chikara",
      "Chillar",
      "Dabas",
      "Dagar",
      "Dagua",
      "Dahiya",
      "Dalal",
      "Dangi",
      "Dara",
      "Deshwal",
      "Dhaka",
      "Dhama",
      "Dhanchak",
      "Dhanda",
      "Dhankhar",
      "Dhillon",
      "Dhomi",
      "Dhoot",
      "Dhoriwal",
      "Dhull",
      "Dollya",
      "Dudi",
      "Duhan",
      "Gahlot",
      "Garhwal",
      "Gehlawat",
      "Ghangas",
      "Gill",
      "Godara",
      "Grewal",
      "Gulia",
      "Heer",
      "Hooda",
      "Jaglon",
      "Jakhar",
      "Jam",
      "Jaswal",
      "Jatasra",
      "Jewlia",
      "Jutrana",
      "Kadian",
      "Kahlon",
      "Kajala",
      "Kakran",
      "Kalen",
      "Kaliramna",
      "Kalkhanse",
      "Karwasra",
      "Kaswan",
      "Kataria",
      "Khakar",
      "Khallia",
      "Kharb",
      "Khatkar",
      "Khatri",
      "Kherwa",
      "Khichad",
      "Kothari",
      "Kuhar",
      "Kulhari",
      "Kundu",
      "Lakhlan",
      "Lakra",
      "lamba",
      "Lamoria",
      "Lather",
      "Lathwal",
      "Latiyan",
      "Laur",
      "Lehga",
      "Maan",
      "Mahan",
      "Malhan",
      "Malik",
      "Mandhan",
      "Mangat",
      "Mann Rai",
      "Meel",
      "Mehria",
      "Mhla",
      "Mohar",
      "Moond",
      "Mor More",
      "Nain",
      "Nairwal",
      "Nandal",
      "Nara",
      "Natt Nat",
      "Nauhr",
      "Nehra",
      "Nitharwal",
      "Ola",
      "Pachehra",
      "Palsania",
      "Panghal",
      "Panwar",
      "Parihar",
      "Pattor",
      "Pawar",
      "Phalaswal",
      "Phogat",
      "Pilania",
      "Pooni",
      "Punia",
      "Rahan",
      "Rajaura",
      "Rana",
      "Rangi",
      "Ranwa",
      "Rao",
      "Rathi",
      "Rawal",
      "Redhu",
      "Repswal",
      "Saharan",
      "Sandhi",
      "Sangawan",
      "Sansanwal",
      "Saran",
      "Saroha",
      "Sarot",
      "Sehrawat",
      "Sheoran",
      "Shokeen",
      "Sidhu",
      "Sikarwar",
      "Sindhu",
      "Singhal",
      "Sinsinwar",
      "Sirohi",
      "Siwach",
      "Solanki",
      "Suhag",
      "Sunda",
      "Takhar",
      "Tanar",
      "Tanwar",
      "Tevatia",
      "Thakaran",
      "Thenua",
      "Thori",
      "Tokas",
      "Tomar",
    ],
  },
  { caste: "Jatav", subCaste: [] },
  { caste: "Kachara", subCaste: [] },
  { caste: "Kadava patel", subCaste: [] },
  { caste: "Kahar", subCaste: [] },
  { caste: "Kaibarta", subCaste: [] },
  { caste: "Kaikaala", subCaste: [] },
  { caste: "Kakkalan", subCaste: [] },
  { caste: "Kalal", subCaste: [] },
  { caste: "Kalanji", subCaste: [] },
  { caste: "Kalar", subCaste: [] },
  { caste: "Kalinga Vysya", subCaste: [] },
  { caste: "Kalita", subCaste: [] },
  { caste: "Kalwar", subCaste: [] },
  { caste: "Kamboj", subCaste: [] },
  { caste: "Kamma", subCaste: [] },
  { caste: "Kanakkan Padanna", subCaste: [] },
  { caste: "Kaniyan", subCaste: [] },
  { caste: "Kansari", subCaste: [] },
  { caste: "Kansyakaar", subCaste: [] },
  { caste: "Kapol", subCaste: [] },
  {
    caste: "Kapu",
    subCaste: ["Kapu All", "Kapu Munnuru", "Kapu Naidu", "Kurupu kapu"],
  },
  { caste: "Karakala Bhakthula", subCaste: [] },
  { caste: "Karana", subCaste: [] },
  { caste: "Karmakar", subCaste: [] },
  { caste: "Karuneegar", subCaste: [] },
  { caste: "Kasar", subCaste: [] },
  { caste: "Kashyap", subCaste: [] },
  { caste: "Katiya", subCaste: [] },
  {
    caste: "Kayastha",
    subCaste: [
      "Ambastha",
      "Ambastha Kayastha",
      "Asthana",
      "Barujibi",
      "Basu",
      "Bhatnagar",
      "Chanda",
      "Dass",
      "Dey",
      "Dhar",
      "Dutta",
      "Ghosh",
      "Gour",
      "Guha",
      "Johri",
      "Karna",
      "Karna",
      "Kars",
      "Kulin",
      "Kulshreshtha",
      "Mathur",
      "Mitra",
      "Nag",
      "Nandi",
      "Nigam",
      "Palit",
      "Paul",
      "Rakshit",
      "Rarhi",
      "Roy",
      "Saxena",
      "Sen",
      "Sil",
      "Sinha",
      "Srivastava",
    ],
  },
  { caste: "Khandayat", subCaste: [] },
  { caste: "Khandelwal", subCaste: [] },
  { caste: "Kharvi", subCaste: [] },
  { caste: "Kharwar", subCaste: [] },
  { caste: "Khatik", subCaste: [] },
  {
    caste: "Khatri",
    subCaste: [
      "Anand",
      "Arora",
      "Bagga",
      "Bahl",
      "Batra",
      "Bedi",
      "Behal",
      "Behl",
      "Beri",
      "Bhalla",
      "Bhandari",
      "Bhasin",
      "Bhatti",
      "Chaddha",
      "Chadha",
      "Chandok",
      "Chaudhary",
      "Chhabra",
      "Chopra",
      "Choudhuri",
      "Dang",
      "Dhawan",
      "Dhir",
      "Duggal",
      "Ghai",
      "Handa",
      "Jaggi",
      "Jairath",
      "Jerath",
      "Jham",
      "Kakkar",
      "Kapur Kapoor",
      "Kehar",
      "Khanna",
      "Khosla",
      "Khukrain",
      "Khullar",
      "Kochar",
      "Kohli",
      "lamba",
      "Mahendru",
      "Malhotra",
      "Marwah",
      "Mehra",
      "Mehta",
      "Nagrath",
      "Nanda",
      "Nanda",
      "Nayyar",
      "Oberoi",
      "Ohri",
      "Passi",
      "Puri",
      "Sabharwal",
      "Sahni",
      "Sareen",
      "Sarin",
      "Sawhney",
      "Sehgal",
      "Sehgal",
      "Sekhri",
      "Seth",
      "Sethi",
      "Sobto",
      "Sodhi",
      "Sondhi",
      "Soni",
      "Sood",
      "Suri",
      "Talwar",
      "Tandon",
      "Thapar",
      "Tuli",
      "Uppal",
      "Vadhera",
      "Verma",
      "Vij",
      "Vohra",
      "Wadhawan",
      "Wahi",
      "Walia",
    ],
  },
  { caste: "Koeri Koiri", subCaste: [] },
  { caste: "Kokanastha Maratha", subCaste: [] },
  { caste: "Koli", subCaste: ["Koli Mahadev", "Koli Patel", "Mangela"] },
  { caste: "Kongu Vellala Gounder", subCaste: [] },
  { caste: "Konkani", subCaste: [] },
  { caste: "Koracha", subCaste: [] },
  { caste: "Korama", subCaste: [] },
  { caste: "Kori", subCaste: [] },
  { caste: "Koshti", subCaste: [] },
  { caste: "Krishnavaka", subCaste: [] },
  {
    caste: "Kshatriya",
    subCaste: [
      "Agnikula Kshatriya",
      "Aguri Ugra Kshatriya",
      "Amethia",
      "Bachhil",
      "Bagel",
      "Baghela Veghela",
      "Bais",
      "Banafar",
      "Bendela",
      "Bhandari",
      "Bharswaj",
      "Bhatraju",
      "Bhatti",
      "Bhavasar Kshatriya",
      "Bisen",
      "Chandel",
      "Chandravanshi",
      "Chauhan",
      "Chopra",
      "Chudasa",
      "Dangi",
      "Dhawan",
      "Dixit",
      "Dogra",
      "Gaherwar",
      "Gargvansi",
      "Gaur",
      "Gautam",
      "Gohil",
      "Hada",
      "Haihaivanshi",
      "Jadon",
      "Jaiswar",
      "Janwar",
      "Kachwaha",
      "Kandera",
      "Kapur",
      "Katiyar",
      "Khandayat",
      "Khanna",
      "Khare",
      "Khati",
      "Kshatriya Rahu Suryavamsam",
      "Kshatriya Raju",
      "Kshatriya Raju",
      "Kshatriya Raju Chandravamsam",
      "Kumawat",
      "Kurmi",
      "Kuruvanshi",
      "Mehra",
      "Nagvanshi",
      "Negi",
      "Nikhumbh",
      "Paliwal",
      "Parihar",
      "Parmar",
      "Pawar",
      "Perika Puragiri Kshatriya",
      "Pundir",
      "Raghuvanshi",
      "Raikwar",
      "Rajkumar",
      "Rajput",
      "Rajwar",
      "Rathor",
      "Rawal",
      "Sahni",
      "Saithwar- Mall",
      "Sami",
      "Sengar",
      "Seth",
      "Shakya",
      "Shrinet",
      "Sikarwar",
      "Singh",
      "Sisodiya",
      "Solanki",
      "Soma Vamsha Arya Kshatriya",
      "Sonvanshi",
      "Suryavanshi",
      "Tandon",
      "Tanwar",
      "Thakur",
      "Thogata Veera Kshatriya",
      "Tomar Tanwar",
      "Tong Kshatriya",
      "Ujjain",
      "Vahi",
      "Vohra",
      "Wadhwa",
    ],
  },
  { caste: "Kshatriya Agnikula", subCaste: [] },
  { caste: "Kudumbi", subCaste: [] },
  { caste: "Kulalar", subCaste: [] },
  { caste: "Kulita", subCaste: [] },
  { caste: "Kumawat", subCaste: [] },
  { caste: "Kumbhar", subCaste: [] },
  { caste: "Kummari", subCaste: [] },
  {
    caste: "Kunbi",
    subCaste: [
      "Ghatode",
      "Dhanoje",
      "Khaire",
      "Khedule",
      "Lonari",
      "Maratha",
      "Tirale",
      "Zade",
    ],
  },
  {
    caste: "Kurmi",
    subCaste: ["Chaudhary", "Ghamaila", "Jaiswar", "Kochyasa", "Mahato"],
  },
  {
    caste: "Kurmi kshatriya",
    subCaste: [
      "Awadhya",
      "Baghel",
      "Chandel",
      "Chandra",
      "Chandrakar",
      "Chandrakar",
      "Chandrawanshi",
      "Chaudhury",
      "Deshmukh",
      "Gangwar",
      "Ghamaila",
      "Jaiswar",
      "Kashyap",
      "Katiyar",
      "Kochaisa",
      "Kumar",
      "Kushwaha Koiri",
      "Mahata",
      "Mahato",
      "Mahto",
      "Parganiha",
      "Patel",
      "Prasad",
      "Rai",
      "Sachan",
      "Singh",
      "Verma",
    ],
  },
  { caste: "Kuruba", subCaste: [] },
  { caste: "Kuruhina shetty", subCaste: [] },
  { caste: "Kurumbar", subCaste: [] },
  { caste: "Kushwaha", subCaste: [] },
  { caste: "Kutchi", subCaste: [] },
  { caste: "Kutchi Gurjar", subCaste: [] },
  { caste: "Lambadi", subCaste: [] },
  { caste: "Leva Patidar", subCaste: [] },
  { caste: "Leva Patil", subCaste: [] },
  {
    caste: "Lingayat",
    subCaste: [
      "Akkasali",
      "Aradhya",
      "Balegala",
      "Banagar",
      "Banajiga",
      "Bhandari",
      "Bilijedaru",
      "Chaturtha",
      "Dikshwant",
      "Ganiga",
      "Gowda",
      "Gowli",
      "Gurav",
      "Hadapada",
      "Hatgar",
      "Hoogar Hugar Jeer",
      "Jadaru",
      "Jangam",
      "Kudu Vokkaliga",
      "Kumbar Kumbara",
      "Kumbhar",
      "Kuruhina Setty",
      "lamba",
      "Lolagonda",
      "Madivala",
      "Malgar",
      "Mali",
      "Neelagar",
      "Neeli Neelagar",
      "Neygi",
      "Nolamba",
      "Pancham",
      "Panchamasali",
      "Pattasali",
      "Reddy Reddi",
      "Sadar",
      "Sajjan",
      "Setty",
      "Shilwant",
      "Shiva Simpi",
      "Vani",
    ],
  },
  { caste: "Lodhi Rajput", subCaste: [] },
  { caste: "Lohana", subCaste: [] },
  { caste: "Lohar", subCaste: [] },
  { caste: "Lubana", subCaste: [] },
  { caste: "Madiga", subCaste: [] },
  { caste: "Mahajan", subCaste: [] },
  { caste: "Mahar", subCaste: [] },
  { caste: "Mahendra", subCaste: [] },
  { caste: "Maheshwari", subCaste: [] },
  { caste: "Mahindra", subCaste: [] },
  { caste: "Mahisya", subCaste: [] },
  { caste: "Majabi Mazhbi", subCaste: [] },
  { caste: "Mala", subCaste: [] },
  { caste: "Mali", subCaste: [] },
  { caste: "Mallah", subCaste: [] },
  { caste: "Manikpuri", subCaste: [] },
  { caste: "Manipuri", subCaste: [] },
  { caste: "Manjhi", subCaste: [] },
  { caste: "Mapila", subCaste: [] },
  {
    caste: "Maratha",
    subCaste: [
      "96 Kuli Maratha",
      "Aramari Gabit",
      "Deshmukh",
      "Deshtha Maratha",
      "Gomantak Maratha",
      "Jhadav",
      "Kokanastha Maratha",
      "Kunbi Dhanoje",
      "Kunbi Khaire",
      "Kunbi Khedule",
      "Kunbi Lonari",
      "Kunbi Maratha",
      "Kunbi Tirale",
      "Malwani",
      "Maratha Kshatriya",
      "Parit",
      "Patil",
      "Sonar",
      "Suthar",
      "Vani",
    ],
  },
  { caste: "Maravar", subCaste: [] },
  { caste: "Maruthuvar", subCaste: [] },
  { caste: "Marwari", subCaste: [] },
  { caste: "Matang", subCaste: [] },
  { caste: "Mathur", subCaste: [] },
  { caste: "Maurya", subCaste: [] },
  { caste: "Meena", subCaste: [] },
  { caste: "Meenavar", subCaste: [] },
  { caste: "Mehra", subCaste: [] },
  { caste: "Menon", subCaste: [] },
  { caste: "Meru", subCaste: [] },
  { caste: "Meru darji", subCaste: [] },
  { caste: "Modak", subCaste: [] },
  { caste: "Mogaveera", subCaste: [] },
  { caste: "Monchi", subCaste: [] },
  { caste: "Motati Reddy", subCaste: [] },
  {
    caste: "Mudaliar",
    subCaste: [
      "Mudailiar Arcot",
      "Mudaliar All",
      "Mudaliar Saiva",
      "Mudaliar Sengupta",
    ],
  },
  { caste: "Mudiraj", subCaste: [] },
  { caste: "Muthuraja", subCaste: [] },
  { caste: "Naagavamsam", subCaste: [] },
  { caste: "Nadar", subCaste: [] },
  { caste: "Nagaralu", subCaste: [] },
  { caste: "Naicker", subCaste: [] },
  {
    caste: "Naidu",
    subCaste: ["Balija Naidu", "Gajula Kavarai", "Kapu Naidu"],
  },
  { caste: "Naik Nayak Nayaka", subCaste: [] },
  {
    caste: "Nair",
    subCaste: [
      "Chekkala Nair",
      "Kartha",
      "Mannadiar",
      "Marar",
      "Nair All",
      "Nair-Vaniya",
      "Veluthedathu",
      "Vilakkithala",
    ],
  },
  { caste: "Namasudra Namosudra", subCaste: [] },
  { caste: "Nambiar", subCaste: [] },
  { caste: "Namboodiri", subCaste: [] },
  { caste: "Namdev Chhipa", subCaste: [] },
  { caste: "Napit", subCaste: [] },
  { caste: "Nath Jogi", subCaste: [] },
  { caste: "Nepali", subCaste: [] },
  { caste: "Nhavi", subCaste: [] },
  { caste: "Nonia", subCaste: [] },
  { caste: "OBC", subCaste: [] },
  { caste: "Oswal", subCaste: [] },
  { caste: "Otari", subCaste: [] },
  { caste: "Others", subCaste: [] },
  { caste: "Padmashali", subCaste: [] },
  { caste: "Pal", subCaste: [] },
  { caste: "Panchal", subCaste: [] },
  { caste: "Panchamsali", subCaste: [] },
  { caste: "Pandaram", subCaste: [] },
  { caste: "Panicker", subCaste: [] },
  { caste: "Parkava Kulam", subCaste: [] },
  { caste: "Pasi", subCaste: [] },
  {
    caste: "Patel",
    subCaste: ["Patel Dodia", "Patel Kadva", "Patel Leva", "Patel Lodhi"],
  },
  { caste: "Pathare Prabhu", subCaste: [] },
  { caste: "Patil", subCaste: [] },
  { caste: "Patnaick", subCaste: [] },
  { caste: "Patra", subCaste: [] },
  { caste: "Perika", subCaste: [] },
  {
    caste: "Pillai",
    subCaste: ["Desikar", "Desikar Thanjavur", "Kodikal Pillai"],
  },
  { caste: "Poosala", subCaste: [] },
  { caste: "Prajapati", subCaste: [] },
  { caste: "Rabari", subCaste: [] },
  { caste: "Raigar", subCaste: [] },
  { caste: "Raikwar", subCaste: [] },
  { caste: "Rajaka", subCaste: [] },
  { caste: "Rajbhar", subCaste: [] },
  { caste: "Rajbongshi", subCaste: [] },
  { caste: "Rajpurohit", subCaste: [] },
  {
    caste: "Rajput",
    subCaste: [
      "Rajput Garhwali",
      "Rajput Kumaoni",
      "Rajput Negi",
      "Ramdasia",
      "Ramgarhia",
      "Ramoshi Berad Bedar",
      "Ravidasia",
      "Rawat",
      "Reddy",
      "Rajput Rohella Tank",
    ],
  },
  { caste: "Reddy", subCaste: [] },
  { caste: "Sadgope", subCaste: [] },
  { caste: "Saha", subCaste: [] },
  { caste: "Sahu", subCaste: [] },
  { caste: "Saini", subCaste: [] },
  { caste: "Saliya", subCaste: [] },
  { caste: "Sathwara", subCaste: [] },
  { caste: "Sawantwadi", subCaste: [] },
  {
    caste: "SC",
    subCaste: [
      "Adi Dravida",
      "Ahirwar",
      "Arunthathiyar",
      "Bairwa",
      "Balai",
      "Dewar Dhibara",
      "Dhanak",
      "Dhobi",
      "Ganda",
      "Ghasi",
      "Holar",
      "Jatav",
      "Julaha",
      "Kanakaan Padonna",
      "Khatik",
      "Kondara",
      "Kori Koli",
      "Kumaoni",
      "Kurava",
      "Kuravan Kuravar",
      "Kuruva",
      "Madiga",
      "Mahar",
      "Mala",
      "Mannan Velon Vannan",
      "Meghwal",
      "Mehra",
      "Mehtar",
      "Paravan Bhartar",
      "Pasi",
      "Paswan Dusadh",
      "Pollon Devandra Kula Vellalan",
      "Ponan",
      "Poundra",
      "Pulaya Chruman",
      "Raigar",
      "Ramdasia",
      "Ravidasia",
      "Relli",
      "Rohit Chamar",
      "Samagar",
      "Sambava",
      "Santhali",
      "Sargara",
      "Satnami",
      "Shilpkar",
      "Sonkar",
      "Thachar",
      "Thandan",
      "Vaduka",
      "Valmiki",
      "Valuvan",
      "Vettuvan",
    ],
  },
  { caste: "ST", subCaste: ["Bhil", "Naika"] },
  { caste: "Senai Thalaivar", subCaste: [] },
  { caste: "Senguntha Mudaliyar", subCaste: [] },
  { caste: "Settibalija", subCaste: [] },
  { caste: "Shah", subCaste: [] },
  { caste: "Shimpi", subCaste: [] },
  {
    caste: "Sindhi",
    subCaste: [
      "Amil",
      "Baibhand",
      "Bhanusali",
      "Bhatia",
      "Chhapru",
      "Hydrabadi",
      "Larai",
      "Larkan",
      "Larkana",
      "Lohana",
      "Rohiri",
      "Sahiti",
      "Sakkhar",
      "Sehwani",
      "Shikarpuri",
      "Thatai",
    ],
  },
  { caste: "SKP", subCaste: [] },
  { caste: "Sonar", subCaste: [] },
  { caste: "Soni", subCaste: [] },
  { caste: "Sood", subCaste: [] },
  { caste: "Sourashtra", subCaste: [] },
  { caste: "Sozhiya Vellalar", subCaste: [] },
  { caste: "Srisayani", subCaste: [] },
  { caste: "SSK", subCaste: [] },
  { caste: "Subarna Banik", subCaste: [] },
  { caste: "Sudi Suri Sundhi Shaundik", subCaste: [] },
  { caste: "Sutar", subCaste: [] },
  { caste: "Swakula sali", subCaste: [] },
  { caste: "Swarnkar", subCaste: [] },
  { caste: "Tamboli", subCaste: [] },
  { caste: "Tanti", subCaste: [] },
  { caste: "Tantuway", subCaste: [] },
  { caste: "Telaga", subCaste: [] },
  { caste: "Teli", subCaste: [] },
  { caste: "Thakkar", subCaste: [] },
  { caste: "Thakur", subCaste: [] },
  { caste: "Thevar Mukkulathor", subCaste: [] },
  { caste: "Thigala", subCaste: [] },
  { caste: "Thiyya", subCaste: [] },
  { caste: "Tili", subCaste: [] },
  { caste: "Togata", subCaste: [] },
  { caste: "Tonk Kshatriya", subCaste: [] },
  { caste: "Tribe", subCaste: [] },
  { caste: "Turupu Kapu", subCaste: [] },
  { caste: "Uppara", subCaste: [] },
  { caste: "Vadar", subCaste: [] },
  { caste: "Vaddera", subCaste: [] },
  { caste: "Vaidiki Velanadu", subCaste: [] },
  { caste: "Vaish", subCaste: [] },
  { caste: "Vaishnav", subCaste: ["Bairagi Swami", "Vaishnav Bhatia"] },
  { caste: "Vaishnav Vanik", subCaste: [] },
  {
    caste: "Vaishnava",
    subCaste: [
      "Brahmin Sri Vaishnava",
      "Chhatada Sri Vaishnava",
      "Sri Vaishnava",
    ],
  },
  { caste: "Vaishya", subCaste: [] },
  { caste: "Vaishya Vani", subCaste: [] },
  { caste: "Vallala", subCaste: [] },
  { caste: "Valluvar", subCaste: [] },
  { caste: "Valmiki", subCaste: [] },
  { caste: "Vania", subCaste: [] },
  { caste: "Vanjari", subCaste: [] },
  { caste: "Vankar", subCaste: [] },
  { caste: "Vannar", subCaste: [] },
  { caste: "Vannia Kula Kshatriyar", subCaste: [] },
  { caste: "Vanniyar", subCaste: [] },
  { caste: "Variar", subCaste: [] },
  { caste: "Varshney", subCaste: [] },
  { caste: "Veershaiva Veera Saivam", subCaste: [] },
  { caste: "Velaan", subCaste: [] },
  { caste: "Velama", subCaste: [] },
  { caste: "Velan", subCaste: [] },
  {
    caste: "Vellalar",
    subCaste: [
      "Aaru Nattu Vellala",
      "Cherakula Vellalar",
      "Devendra Kula Vellalar",
      "Isai Vellalar",
      "Karkathar",
      "Saiva Vellalar",
      "Sozhiya Vellalar",
      "Vellalar All",
    ],
  },
  { caste: "Vettuva Gounder", subCaste: [] },
  { caste: "Vishwakarma", subCaste: [] },
  { caste: "Vokkaliga", subCaste: [] },
  { caste: "Vysya", subCaste: [] },
  {
    caste: "Yadav Yadava",
    subCaste: [
      "Aheer Ahir",
      "Daddi",
      "Das",
      "Dhador",
      "Erragola",
      "Gadri Gadariya",
      "Gauda",
      "Gawli",
      "Goal Gola Golla",
      "Gop Gopal Gopala",
      "Goriya",
      "Gwala",
      "Gwalvanshi",
      "Jadav",
      "Kohar",
      "Korna",
      "Krishnauth",
      "Kurudas Gollas",
      "Kuruma",
      "Mandal",
      "Manjrauth",
      "Nandvanshi",
      "Pakanati",
      "Puja",
      "Raut",
      "Suryavanshi",
      "Thethwar",
      "Yadav Golla",
      "Yaduvanshi",
    ],
  },
  { caste: "Yellapu", subCaste: [] },
];

export const Feeder = { Languages, Castes };
